export const GET_BREAKING_BAD_REQUEST = 'GET_BREAKING_BAD_REQUEST'
export const GET_BREAKING_BAD_SUCCESS = 'GET_BREAKING_BAD_SUCCESS'
export const GET_BREAKING_BAD_FAIL = 'GET_BREAKING_BAD_FAIL'


export const SET_BREAKING_BAD_REQUEST = 'SET_BREAKING_BAD_REQUEST'
export const setBreakingBadRequest = (text) => (
    {
        type: SET_BREAKING_BAD_REQUEST,
        text: text
    })
export const SET_BREAKING_BAD_SUCCESS = 'SET_BREAKING_BAD_SUCCESS'
export const SET_BREAKING_BAD_FAIL = 'SET_BREAKING_BAD_FAIL'
